### ISSUE TITLE
[Question] Can this extension be used in tandem with another local server login method?

### ISSUE THREAD

**Issue by Psirax** [soulwing/cas-extension#11]
Hello!

I am writing a Java EE Web App that needs to authenticate with our CAS server for _most_ of the application. However, for select areas, I need to be able to determine (through an intermediary page asking if they have CAS credentials or local credentials) if they should go to CAS or go to a local login page to take their credentials and authenticate against our local credential store (as these users don't exist in our CAS server). Essentially, I need to be able to use CAS AND another login page, depending on where in the application they're going. 

I know that this is likely not a good idea, nor the ideal way to use CAS, however this is the environment I must work with. Thus, is it feasibly possible to do this using this CAS Extension in a single web app?

Thank you for your time,
Eric

**Comment by ceharris** [comment]
The Java EE spec allows only one authentication/authorization mechanism in a given web application, so what you're asking to do isn't possible within the confines of what you can specify through declarative security metadata (e.g. web.xml, annotations). There are, however, a couple of options you can use to do what you suggest.

1. Use an outboard service such as [Keycloak](http://www.keycloak.org/) to handle authentication. I'm fairly certain that using more than identity provider or authentication mechanism for a given application is a supported use case for Keycloak.
2. You could do all authentication/authorization within the application itself using a framework like Spring Security. This works best if you're really willing to embrace most/all of the Spring Framework instead of using modern Java EE.

Hope this helps!

**Comment by Psirax** [comment]
That's what I thought based on the research I've been doing. I appreciate the recommendations!

Thanks,
Eric
